from django.urls import path

from . import views


urlpatterns = [
    path(
        "deletion/",
        views.customer_account_deletion,
        name="customer_account_deletion",
    ),
    path(
        "deletion/request/",
        views.customer_account_deletion_authenticated,
        name="customer_account_deletion_authenticated",
    ),
    path(
        "deletion/submitted/",
        views.customer_account_deletion_submitted,
        name="customer_account_deletion_submitted",
    ),
    path(
        "deletion/verify/<uuid:request_id>/<str:token>/",
        views.customer_account_deletion_verify,
        name="customer_account_deletion_verify",
    ),
    path(
        "deletion/verified/",
        views.customer_account_deletion_verified,
        name="customer_account_deletion_verified",
    ),
    path(
        "owner/deletion-requests/",
        views.customer_account_deletion_list,
        name="customer_account_deletion_list",
    ),
    path(
        "owner/deletion-requests/<uuid:request_id>/",
        views.customer_account_deletion_detail_view,
        name="customer_account_deletion_detail",
    ),
    path(
        "owner/deletion-requests/<uuid:request_id>/hold/",
        views.customer_account_deletion_hold,
        name="customer_account_deletion_hold",
    ),
    path(
        "register/",
        views.customer_registration,
        name="customer_registration",
    ),
    path(
        "register/submitted/",
        views.customer_registration_submitted,
        name="customer_registration_submitted",
    ),
    path(
        "registrations/verify/<uuid:application_id>/<str:token>/",
        views.customer_registration_verify,
        name="customer_registration_verify",
    ),
    path(
        "registrations/verified/",
        views.customer_registration_verified,
        name="customer_registration_verified",
    ),
    path(
        "owner/registrations/",
        views.customer_registration_list,
        name="customer_registration_list",
    ),
    path(
        "owner/registrations/<uuid:application_id>/",
        views.customer_registration_detail,
        name="customer_registration_detail",
    ),
    path(
        "owner/registrations/<uuid:application_id>/approve/",
        views.customer_registration_approve,
        name="customer_registration_approve",
    ),
    path(
        "owner/registrations/<uuid:application_id>/reject/",
        views.customer_registration_reject,
        name="customer_registration_reject",
    ),
    path(
        "owner/registrations/<uuid:application_id>/resend-verification/",
        views.customer_registration_resend_verification,
        name="customer_registration_resend_verification",
    ),
    path(
        "invitations/<uuid:invitation_id>/<str:token>/",
        views.customer_invitation_accept,
        name="customer_invitation_accept",
    ),
]
