# Generated by Django 6.0.4 on 2026-08-18 05:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'customer_number'],
            },
        ),
        migrations.CreateModel(
            name='SchemePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('minimum_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(12)])),
                ('default_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(12)])),
                ('amount_rule', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], max_length=10)),
                ('frequency_rule', models.CharField(choices=[('ONCE_PER_MONTH', 'Once per month'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('fixed_contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_contribution', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allow_contributions_after_eligibility', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_months__gte', 12)), name='plan_minimum_months_gte_12'), models.CheckConstraint(condition=models.Q(('default_months__gte', models.F('minimum_months'))), name='plan_default_months_gte_minimum'), models.CheckConstraint(condition=models.Q(('minimum_contribution__gt', 0)), name='plan_minimum_contribution_positive'), models.CheckConstraint(condition=models.Q(('maximum_contribution__isnull', True), ('maximum_contribution__gte', models.F('minimum_contribution')), _connector='OR'), name='plan_maximum_gte_minimum'), models.CheckConstraint(condition=models.Q(('amount_rule', 'VARIABLE'), ('fixed_contribution_amount__gt', 0), _connector='OR'), name='plan_fixed_amount_positive_when_fixed')],
            },
        ),
        migrations.CreateModel(
            name='SchemeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_number', models.CharField(max_length=24, unique=True)),
                ('start_date', models.DateField()),
                ('agreed_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12)])),
                ('eligible_from', models.DateField()),
                ('savings_mode', models.CharField(choices=[('CASH', 'Cash Savings'), ('GOLD', 'Gold Savings'), ('SILVER', 'Silver Savings')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REDEMPTION_ELIGIBLE', 'Redemption eligible'), ('REDEEMED', 'Redeemed')], default='ACTIVE', max_length=24)),
                ('amount_rule_snapshot', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], max_length=10)),
                ('frequency_rule_snapshot', models.CharField(choices=[('ONCE_PER_MONTH', 'Once per month'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('fixed_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allow_post_eligibility_contributions_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_accounts', to='schemes.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_accounts', to='schemes.schemeplan')),
            ],
            options={
                'ordering': ['-start_date', 'scheme_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('agreed_months__gte', 12)), name='account_agreed_months_gte_12'), models.CheckConstraint(condition=models.Q(('minimum_amount_snapshot__gt', Decimal('0'))), name='account_minimum_amount_positive'), models.CheckConstraint(condition=models.Q(('maximum_amount_snapshot__isnull', True), ('maximum_amount_snapshot__gte', models.F('minimum_amount_snapshot')), _connector='OR'), name='account_maximum_gte_minimum')],
            },
        ),
    ]
