# Generated by Django 6.0.4 on 2026-08-18 06:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_period', models.DateField(help_text='First calendar day of the contribution month.')),
                ('frequency_rule_snapshot', models.CharField(choices=[('ONCE_PER_MONTH', 'Once per month'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('payment_gateway', models.CharField(max_length=30)),
                ('gateway_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('scheme_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='schemes.schemeaccount')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contrib_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='contribution_amount_positive'), models.CheckConstraint(condition=models.Q(('contribution_period__day', 1)), name='contribution_period_first_day'), models.CheckConstraint(condition=models.Q(models.Q(('gateway_reference__isnull', False), ('paid_at__isnull', False), ('status', 'PAID')), models.Q(('paid_at__isnull', True), ('status__in', ['PENDING', 'FAILED'])), _connector='OR'), name='paid_contribution_has_confirmation'), models.UniqueConstraint(condition=models.Q(('frequency_rule_snapshot', 'ONCE_PER_MONTH'), ('status', 'PAID')), fields=('scheme_account', 'contribution_period'), name='one_paid_contribution_per_account_period')],
            },
        ),
    ]
