# Generated by Django 6.0.4 on 2026-08-18 06:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', '24K Gold'), ('SILVER', 'Silver')], max_length=10)),
                ('provider', models.CharField(max_length=50)),
                ('provider_timestamp', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('provider_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('applied_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purity', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'ordering': ['-fetched_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('metal__in', ['GOLD', 'SILVER'])), name='rate_snapshot_valid_metal'), models.CheckConstraint(condition=models.Q(('provider_rate__gt', Decimal('0'))), name='provider_rate_positive'), models.CheckConstraint(condition=models.Q(('applied_rate__gt', Decimal('0'))), name='applied_rate_positive'), models.CheckConstraint(condition=models.Q(('purity__gt', Decimal('0')), ('purity__lte', Decimal('1'))), name='rate_snapshot_valid_purity')],
            },
        ),
        migrations.CreateModel(
            name='MetalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', '24K Gold'), ('SILVER', 'Silver')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='metal_allocation', to='schemes.contribution')),
                ('rate_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='metal_allocation', to='schemes.ratesnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('metal__in', ['GOLD', 'SILVER'])), name='metal_allocation_valid_metal'), models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='metal_allocation_quantity_positive')],
            },
        ),
    ]
