# Generated by Django 6.0.4 on 2026-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_ratesnapshot_metalallocation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contribution',
            name='paid_contribution_has_confirmation',
        ),
        migrations.RemoveConstraint(
            model_name='contribution',
            name='one_paid_contribution_per_account_period',
        ),
        migrations.AddField(
            model_name='contribution',
            name='allocation_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='allocation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PAID_UNALLOCATED', 'Paid — allocation pending'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gateway_reference__isnull', False), ('paid_at__isnull', False), ('status__in', ['PAID', 'PAID_UNALLOCATED'])), models.Q(('paid_at__isnull', True), ('status__in', ['PENDING', 'FAILED'])), _connector='OR'), name='paid_contribution_has_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency_rule_snapshot', 'ONCE_PER_MONTH'), ('status__in', ['PAID', 'PAID_UNALLOCATED'])), fields=('scheme_account', 'contribution_period'), name='one_paid_contribution_per_account_period'),
        ),
    ]
