# Generated by Django 6.0.4 on 2026-08-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_remove_contribution_paid_contribution_has_confirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(condition=models.Q(('frequency_rule_snapshot', 'ONCE_PER_MONTH'), ('payment_gateway', 'razorpay'), ('status', 'PENDING')), fields=('scheme_account', 'contribution_period'), name='one_pending_razorpay_monthly_payment'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='schemes.contribution'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['gateway', 'status', 'received_at'], name='webhook_gateway_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='unique_gateway_webhook_event'),
        ),
    ]
