# Generated by Django 6.0.4 on 2026-08-18 08:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_paymentwebhookevent_contribution_gateway_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_number', models.CharField(max_length=24, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('settlement_type', models.CharField(choices=[('JEWELLERY_PURCHASE', 'Jewellery purchase'), ('CASH', 'Cash'), ('METAL', 'Metal')], max_length=24)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gold_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('silver_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('scheme_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='schemes.schemeaccount')),
            ],
            options={
                'ordering': ['-completed_at', '-pk'],
                'indexes': [models.Index(fields=['scheme_account', 'status', 'completed_at'], name='redemption_account_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cash_amount__gt', Decimal('0')), ('gold_quantity__isnull', True), ('silver_quantity__isnull', True)), models.Q(('cash_amount__isnull', True), ('gold_quantity__gt', Decimal('0')), ('silver_quantity__isnull', True)), models.Q(('cash_amount__isnull', True), ('gold_quantity__isnull', True), ('silver_quantity__gt', Decimal('0'))), _connector='OR'), name='redemption_exactly_one_positive_entitlement')],
            },
        ),
    ]
