# Generated by Django 6.0.4 on 2026-08-18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def classify_existing_cash_redemptions(apps, schema_editor):
    Redemption = apps.get_model("schemes", "Redemption")
    Redemption.objects.filter(cash_amount__isnull=False).update(
        cash_principal_amount=models.F("cash_amount"),
        cash_bonus_amount=Decimal("0.00"),
    )


def clear_cash_redemption_components(apps, schema_editor):
    Redemption = apps.get_model("schemes", "Redemption")
    Redemption.objects.update(
        cash_principal_amount=None,
        cash_bonus_amount=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0006_redemption"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemption",
            name="cash_bonus_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="redemption",
            name="cash_principal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schemeaccount",
            name="cash_bonus_minimum_months_snapshot",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="schemeaccount",
            name="cash_bonus_percentage_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="schemeaccount",
            name="cash_bonus_policy_version_snapshot",
            field=models.CharField(default="CASH-BONUS-V1", max_length=30),
        ),
        migrations.AddField(
            model_name="schemeplan",
            name="cash_bonus_minimum_months",
            field=models.PositiveSmallIntegerField(
                default=12,
                validators=[django.core.validators.MinValueValidator(12)],
            ),
        ),
        migrations.AddField(
            model_name="schemeplan",
            name="cash_bonus_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.RunPython(
            classify_existing_cash_redemptions,
            clear_cash_redemption_components,
        ),
        migrations.AddConstraint(
            model_name="redemption",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        cash_amount__isnull=True,
                        cash_principal_amount__isnull=True,
                        cash_bonus_amount__isnull=True,
                    )
                    | models.Q(
                        cash_amount__gt=Decimal("0"),
                        cash_principal_amount__gte=Decimal("0"),
                        cash_bonus_amount__gte=Decimal("0"),
                        cash_amount=(
                            models.F("cash_principal_amount")
                            + models.F("cash_bonus_amount")
                        ),
                    )
                ),
                name="redemption_cash_components_match_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    cash_bonus_percentage_snapshot__gte=Decimal("0"),
                    cash_bonus_percentage_snapshot__lte=Decimal("100"),
                ),
                name="account_cash_bonus_percentage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(cash_bonus_minimum_months_snapshot__gte=12),
                name="account_cash_bonus_months_gte_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    cash_bonus_percentage__gte=Decimal("0"),
                    cash_bonus_percentage__lte=Decimal("100"),
                ),
                name="plan_cash_bonus_percentage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeplan",
            constraint=models.CheckConstraint(
                condition=models.Q(cash_bonus_minimum_months__gte=12),
                name="plan_cash_bonus_months_gte_12",
            ),
        ),
    ]
