# Generated by Django 6.0.4 on 2026-08-18 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_cash_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('MANUAL_RATE_OVERRIDE', 'Manual rate override'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry')], max_length=40)),
                ('actor_label', models.CharField(max_length=254)),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_audit_events', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='schemes.contribution')),
                ('rate_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='schemes.ratesnapshot')),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='schemes.redemption')),
                ('scheme_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='schemes.schemeaccount')),
                ('scheme_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='schemes.schemeplan')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audit_action_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_label', ''), _negated=True), name='audit_event_actor_label_required'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='audit_event_reason_required')],
            },
        ),
        migrations.CreateModel(
            name='RedemptionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_number', models.CharField(max_length=24, unique=True)),
                ('reason', models.TextField()),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_redemption_reversals', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='schemes.redemption')),
            ],
            options={
                'ordering': ['-reversed_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='redemption_reversal_reason_required')],
            },
        ),
    ]
