# Generated by Django 6.0.4 on 2026-08-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0011_razorpay_gateway_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contribution',
            name='paid_contribution_has_confirmation',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('SCHEME_RATE_PUBLICATION', 'Scheme rate publication'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry'), ('PAYMENT_ORDER_RECONCILIATION', 'Payment order reconciliation')], max_length=40),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PAID_UNALLOCATED', 'Paid — allocation pending'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gateway_reference__isnull', False), ('paid_at__isnull', False), ('status__in', ['PAID', 'PAID_UNALLOCATED'])), models.Q(('paid_at__isnull', True), ('status__in', ['PENDING', 'FAILED', 'ABANDONED'])), _connector='OR'), name='paid_contribution_has_confirmation'),
        ),
    ]
