# Generated by Django 6.0.4 on 2026-08-31 04:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_payment_operations_control(apps, schema_editor):
    PaymentOperationsControl = apps.get_model(
        "schemes", "PaymentOperationsControl"
    )
    PaymentScheduleWindow = apps.get_model("schemes", "PaymentScheduleWindow")
    control, _created = PaymentOperationsControl.objects.get_or_create(pk=1)
    for weekday in range(7):
        PaymentScheduleWindow.objects.get_or_create(
            control=control,
            weekday=weekday,
            defaults={
                "enabled": True,
                "opens_at": datetime.time(9, 0),
                "closes_at": datetime.time(13 if weekday == 6 else 21, 0),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0012_abandoned_razorpay_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('SCHEME_RATE_PUBLICATION', 'Scheme rate publication'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry'), ('PAYMENT_ORDER_RECONCILIATION', 'Payment order reconciliation'), ('PAYMENT_OPERATIONS_CHANGE', 'Payment operations change')], max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentOperationsControl',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('require_current_day_rate', models.BooleanField(default=True)),
                ('global_pause', models.BooleanField(default=False)),
                ('gold_pause', models.BooleanField(default=False)),
                ('silver_pause', models.BooleanField(default=False)),
                ('customer_message', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_operations_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentScheduleWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('enabled', models.BooleanField(default=True)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_windows', to='schemes.paymentoperationscontrol')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('control', 'weekday'), name='payment_schedule_one_window_per_day'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='payment_schedule_valid_weekday'), models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='payment_schedule_positive_window')],
            },
        ),
        migrations.RunPython(
            seed_payment_operations_control,
            migrations.RunPython.noop,
        ),
    ]
