# Generated by Django 6.0.4 on 2026-08-31 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0013_payment_operations_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='failure_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('SCHEME_RATE_PUBLICATION', 'Scheme rate publication'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry'), ('PAYMENT_ORDER_RECONCILIATION', 'Payment order reconciliation'), ('PAYMENT_OPERATIONS_CHANGE', 'Payment operations change'), ('WEBHOOK_RECOVERY', 'Webhook recovery')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review required')], default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='WebhookProcessingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PROVIDER_DELIVERY', 'Provider delivery'), ('OWNER_RECOVERY', 'Owner recovery')], max_length=30)),
                ('outcome', models.CharField(choices=[('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('ALREADY_FINAL', 'Already final'), ('REVIEW_REQUIRED', 'Review required'), ('TRANSIENT_FAILURE', 'Transient failure'), ('ELIGIBLE_FOR_RECOVERY', 'Eligible for recovery'), ('ALREADY_PROCESSED', 'Already processed')], max_length=30)),
                ('actor_label', models.CharField(max_length=254)),
                ('reason', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('detail', models.TextField(blank=True)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_processing_attempts', to=settings.AUTH_USER_MODEL)),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_attempts', to='schemes.paymentwebhookevent')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['webhook_event', 'created_at'], name='webhook_attempt_event_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_label', ''), _negated=True), name='webhook_attempt_actor_required'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='webhook_attempt_reason_required')],
            },
        ),
    ]
