# Generated by Django 6.0.4 on 2026-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0015_graded_metal_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalallocation',
            name='metal',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schemerate',
            name='metal',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schemerate',
            name='purity',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
