# Generated by Django 6.0.4 on 2026-09-03 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_payment_channels(apps, schema_editor):
    Contribution = apps.get_model("schemes", "Contribution")
    Contribution.objects.filter(payment_gateway="razorpay").update(
        payment_channel="RAZORPAY"
    )
    Contribution.objects.exclude(payment_gateway="razorpay").update(
        payment_channel="MOCK"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0017_contribution_checkout_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InStoreCashContributionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_number', models.CharField(max_length=32, unique=True)),
                ('reason_code', models.CharField(choices=[('DUPLICATE_ENTRY', 'Duplicate entry'), ('WRONG_ACCOUNT', 'Wrong scheme account'), ('WRONG_AMOUNT', 'Wrong amount'), ('CASH_NOT_RECEIVED', 'Cash was not received')], max_length=24)),
                ('reason', models.TextField()),
                ('processed_by_label', models.CharField(max_length=254)),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reversed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InStoreCashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_reference', models.CharField(max_length=32, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paper_receipt_number', models.CharField(blank=True, help_text="Optional unique number from the showroom's paper receipt book.", max_length=80, null=True, unique=True)),
                ('received_by_label', models.CharField(max_length=254)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='contribution',
            name='paid_contribution_has_confirmation',
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_channel',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay online'), ('IN_STORE_CASH', 'In-store cash'), ('MOCK', 'Mock payment')], default='MOCK', max_length=20),
        ),
        migrations.RunPython(backfill_payment_channels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('IN_STORE_CASH_RECEIPT', 'In-store cash receipt'), ('IN_STORE_CASH_REVERSAL', 'In-store cash reversal'), ('SCHEME_RATE_PUBLICATION', 'Scheme rate publication'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry'), ('PAYMENT_ORDER_RECONCILIATION', 'Payment order reconciliation'), ('PAYMENT_OPERATIONS_CHANGE', 'Payment operations change'), ('WEBHOOK_RECOVERY', 'Webhook recovery')], max_length=40),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PAID_UNALLOCATED', 'Paid — allocation pending'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gateway_reference__isnull', False), ('paid_at__isnull', False), ('status__in', ['PAID', 'PAID_UNALLOCATED', 'REVERSED'])), models.Q(('paid_at__isnull', True), ('status__in', ['PENDING', 'FAILED', 'ABANDONED'])), _connector='OR'), name='paid_contribution_has_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_channel', 'RAZORPAY'), ('payment_gateway', 'razorpay')), models.Q(('payment_channel', 'IN_STORE_CASH'), ('payment_gateway', 'in_store_cash')), models.Q(models.Q(('payment_gateway__in', ['razorpay', 'in_store_cash']), _negated=True), ('payment_channel', 'MOCK')), _connector='OR'), name='contribution_payment_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_channel', 'IN_STORE_CASH'), _negated=True), models.Q(('checkout_expires_at__isnull', True), ('gateway_mode', ''), ('gateway_order_id__isnull', True), ('gateway_signature', ''), ('status__in', ['PAID', 'PAID_UNALLOCATED', 'REVERSED'])), _connector='OR'), name='in_store_cash_fields_valid'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), ('payment_channel', 'IN_STORE_CASH'), _connector='OR'), name='reversed_contribution_is_cash'),
        ),
        migrations.AddField(
            model_name='instorecashcontributionreversal',
            name='contribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reversal', to='schemes.contribution'),
        ),
        migrations.AddField(
            model_name='instorecashcontributionreversal',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_in_store_cash_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instorecashreceipt',
            name='contribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipt', to='schemes.contribution'),
        ),
        migrations.AddField(
            model_name='instorecashreceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_in_store_cash_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='instorecashcontributionreversal',
            index=models.Index(fields=['reversed_at'], name='cash_reversal_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='instorecashcontributionreversal',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_number', ''), _negated=True), name='cash_reversal_number_required'),
        ),
        migrations.AddConstraint(
            model_name='instorecashcontributionreversal',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='cash_reversal_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='instorecashcontributionreversal',
            constraint=models.CheckConstraint(condition=models.Q(('processed_by_label', ''), _negated=True), name='cash_reversal_actor_label_required'),
        ),
        migrations.AddIndex(
            model_name='instorecashreceipt',
            index=models.Index(fields=['received_at'], name='cash_receipt_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='instorecashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_reference', ''), _negated=True), name='cash_receipt_reference_required'),
        ),
        migrations.AddConstraint(
            model_name='instorecashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received_by_label', ''), _negated=True), name='cash_receipt_actor_label_required'),
        ),
    ]
