# Generated by Django 6.0.4 on 2026-09-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0018_in_store_cash_contributions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("UPCOMING_ELIGIBILITY", "Upcoming eligibility"),
                            ("ALLOCATION_EXCEPTION", "Allocation exception"),
                            ("COMPLETED_REDEMPTION", "Completed redemption"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("OWNER", "Owner")],
                        max_length=10,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("event_date", models.DateField()),
                (
                    "eligibility_lead_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="schemes.contribution",
                    ),
                ),
                (
                    "redemption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="schemes.redemption",
                    ),
                ),
                (
                    "scheme_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="schemes.schemeaccount",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.CreateModel(
            name="SchemeReminderDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted by email provider"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("backend", models.CharField(max_length=200)),
                ("accepted_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="schemes.schemereminder",
                    ),
                ),
            ],
            options={"ordering": ["attempted_at", "pk"]},
        ),
        migrations.AddIndex(
            model_name="schemereminder",
            index=models.Index(
                fields=["kind", "event_date"],
                name="scheme_reminder_kind_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemereminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    kind__in=[
                        "UPCOMING_ELIGIBILITY",
                        "ALLOCATION_EXCEPTION",
                        "COMPLETED_REDEMPTION",
                    ]
                ),
                name="scheme_reminder_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemereminder",
            constraint=models.CheckConstraint(
                condition=models.Q(audience__in=["CUSTOMER", "OWNER"]),
                name="scheme_reminder_audience_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemereminder",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        kind="UPCOMING_ELIGIBILITY",
                        contribution__isnull=True,
                        redemption__isnull=True,
                        eligibility_lead_days__isnull=False,
                    )
                    | models.Q(
                        kind="ALLOCATION_EXCEPTION",
                        contribution__isnull=False,
                        redemption__isnull=True,
                        eligibility_lead_days__isnull=True,
                    )
                    | models.Q(
                        kind="COMPLETED_REDEMPTION",
                        contribution__isnull=True,
                        redemption__isnull=False,
                        eligibility_lead_days__isnull=True,
                    )
                ),
                name="scheme_reminder_target_shape_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="schemereminderdeliveryattempt",
            index=models.Index(
                fields=["reminder", "attempted_at"],
                name="scheme_rem_attempt_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemereminderdeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(outcome__in=["ACCEPTED", "FAILED"]),
                name="scheme_reminder_attempt_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemereminderdeliveryattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        outcome="ACCEPTED",
                        accepted_count=1,
                        error_code="",
                    )
                    | (
                        models.Q(outcome="FAILED", accepted_count=0)
                        & ~models.Q(error_code="")
                    )
                ),
                name="scheme_reminder_attempt_result_valid",
            ),
        ),
    ]
