# Generated by Django 6.0.4 on 2026-09-04 14:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0019_scheme_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_ENROLMENT', 'Customer enrolment'), ('ENROLMENT_REQUEST_SUBMITTED', 'Enrolment request submitted'), ('ENROLMENT_REQUEST_WITHDRAWN', 'Enrolment request withdrawn'), ('ENROLMENT_REQUEST_DECLINED', 'Enrolment request declined'), ('ENROLMENT_REQUEST_EXPIRED', 'Enrolment request expired'), ('ENROLMENT_REQUEST_ENROLLED', 'Enrolment request enrolled'), ('SCHEME_CHANGE', 'Scheme change'), ('MANUAL_PAYMENT_CORRECTION', 'Manual payment correction'), ('IN_STORE_CASH_RECEIPT', 'In-store cash receipt'), ('IN_STORE_CASH_REVERSAL', 'In-store cash reversal'), ('SCHEME_RATE_PUBLICATION', 'Scheme rate publication'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('ALLOCATION_RETRY', 'Allocation retry'), ('PAYMENT_ORDER_RECONCILIATION', 'Payment order reconciliation'), ('PAYMENT_OPERATIONS_CHANGE', 'Payment operations change'), ('WEBHOOK_RECOVERY', 'Webhook recovery')], max_length=40),
        ),
        migrations.CreateModel(
            name='SchemeEnrolmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name_snapshot', models.CharField(max_length=120)),
                ('plan_code_snapshot', models.CharField(max_length=30)),
                ('requested_contribution_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requested_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12)])),
                ('customer_message', models.TextField(blank=True)),
                ('amount_rule_snapshot', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], max_length=10)),
                ('frequency_rule_snapshot', models.CharField(choices=[('ONCE_PER_MONTH', 'Once per month'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('fixed_contribution_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_contribution_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_contribution_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_months_snapshot', models.PositiveSmallIntegerField()),
                ('default_months_snapshot', models.PositiveSmallIntegerField()),
                ('allow_post_eligibility_contributions_snapshot', models.BooleanField()),
                ('disclosure_version', models.CharField(max_length=30)),
                ('disclosure_accepted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING_OWNER_REVIEW', 'Pending owner review'), ('WITHDRAWN', 'Withdrawn'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('ENROLLED', 'Enrolled')], default='PENDING_OWNER_REVIEW', max_length=24)),
                ('expires_at', models.DateTimeField()),
                ('decided_by_label', models.CharField(blank=True, max_length=254)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolment_requests', to='schemes.customer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_scheme_enrolment_requests', to=settings.AUTH_USER_MODEL)),
                ('metal_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolment_requests', to='schemes.metalgrade')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolment_requests', to='schemes.schemeplan')),
                ('scheme_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolment_request', to='schemes.schemeaccount')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='enrol_req_status_expiry_idx'), models.Index(fields=['customer', 'created_at'], name='enrol_req_customer_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING_OWNER_REVIEW')), fields=('customer', 'plan', 'metal_grade'), name='enrol_request_unique_pending_offering'), models.CheckConstraint(condition=models.Q(('requested_months__gte', 12)), name='enrol_request_months_gte_12'), models.CheckConstraint(condition=models.Q(('requested_months__gte', models.F('minimum_months_snapshot'))), name='enrol_request_months_gte_minimum'), models.CheckConstraint(condition=models.Q(('minimum_contribution_snapshot__gt', Decimal('0'))), name='enrol_request_minimum_positive'), models.CheckConstraint(condition=models.Q(('maximum_contribution_snapshot__isnull', True), ('maximum_contribution_snapshot__gte', models.F('minimum_contribution_snapshot')), _connector='OR'), name='enrol_request_maximum_valid'), models.CheckConstraint(condition=models.Q(('requested_contribution_amount__gte', models.F('minimum_contribution_snapshot')), models.Q(('maximum_contribution_snapshot__isnull', True), ('requested_contribution_amount__lte', models.F('maximum_contribution_snapshot')), _connector='OR')), name='enrol_request_amount_within_offer'), models.CheckConstraint(condition=models.Q(models.Q(('amount_rule_snapshot', 'FIXED'), ('fixed_contribution_amount_snapshot__isnull', False), ('requested_contribution_amount', models.F('fixed_contribution_amount_snapshot'))), models.Q(('amount_rule_snapshot', 'VARIABLE'), ('fixed_contribution_amount_snapshot__isnull', True)), _connector='OR'), name='enrol_request_amount_rule_valid'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('decided_by_label', ''), ('decision_reason', ''), ('scheme_account__isnull', True), ('status', 'PENDING_OWNER_REVIEW')), models.Q(('decided_at__isnull', False), ('scheme_account__isnull', True), ('status__in', ['WITHDRAWN', 'DECLINED', 'EXPIRED']), models.Q(('decided_by_label', ''), _negated=True), models.Q(('decision_reason', ''), _negated=True)), models.Q(('decided_at__isnull', False), ('scheme_account__isnull', False), ('status', 'ENROLLED'), models.Q(('decided_by_label', ''), _negated=True), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='enrol_request_lifecycle_shape_valid'), models.CheckConstraint(condition=models.Q(('disclosure_version', ''), _negated=True), name='enrol_request_disclosure_required'), models.CheckConstraint(condition=models.Q(models.Q(('plan_name_snapshot', ''), _negated=True), models.Q(('plan_code_snapshot', ''), _negated=True)), name='enrol_request_plan_identity'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('disclosure_accepted_at'))), name='enrol_request_expiry_after_consent')],
            },
        ),
    ]
