# Generated by Django 6.0.4 on 2026-08-25 09:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='About us', max_length=80)),
                ('introduction', models.TextField(help_text='A concise introduction to the business. Do not enter plan or policy terms.', max_length=600)),
                ('business_story_heading', models.CharField(default='Personal service, supported by dependable records', max_length=120)),
                ('business_story', wagtail.fields.RichTextField(help_text='Business background only. Savings, payment, eligibility, and policy facts remain application-owned below this section.')),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OurStoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='The people behind the name', max_length=80)),
                ('introduction', models.TextField(max_length=600)),
                ('business_owner_name', models.CharField(default='Dilip Kumar', max_length=120)),
                ('business_owner_role', models.CharField(default='Owner & business lead', max_length=120)),
                ('business_owner_tagline', models.CharField(default='Computer science engineer by qualification, businessman by heart.', max_length=240)),
                ('business_owner_bio', wagtail.fields.RichTextField()),
                ('business_owner_image_alt', models.CharField(blank=True, max_length=160)),
                ('developer_name', models.CharField(default='Rajesh Rathod H', max_length=120)),
                ('developer_role', models.CharField(default='Developer', max_length=120)),
                ('developer_tagline', models.CharField(default='Software developer by heart.', max_length=240)),
                ('developer_bio', wagtail.fields.RichTextField()),
                ('developer_email', models.EmailField(default='rajeshrathodh@gmail.com', max_length=254)),
                ('developer_image_alt', models.CharField(blank=True, max_length=160)),
                ('partnership_heading', models.CharField(default='Built together, for the customers they serve', max_length=160)),
                ('partnership_story', wagtail.fields.RichTextField()),
                ('business_owner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('developer_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Our Story page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
