# Generated by Django 6.0.4 on 2026-08-26 10:27

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def require_unique_nonblank_user_emails(apps, schema_editor):
    user_model = apps.get_model("accounts", "CustomUser")
    duplicate_count = (
        user_model.objects.exclude(email="")
        .annotate(normalized_email=django.db.models.functions.text.Lower("email"))
        .values("normalized_email")
        .annotate(matches=models.Count("pk"))
        .filter(matches__gt=1)
        .count()
    )
    if duplicate_count:
        raise RuntimeError(
            "Cannot enforce unique customer login emails: duplicate nonblank "
            "case-insensitive email groups exist. Run "
            "`python manage.py check_auth_email_integrity`, resolve each account "
            "deliberately, and rerun the migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_by_label', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_failed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.CharField(blank=True, max_length=100)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RunPython(
            require_unique_nonblank_user_emails,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='customerinvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_customer_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerinvitation',
            index=models.Index(fields=['user', 'created_at'], name='customer_invite_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='customer_invitation_not_accepted_and_revoked'),
        ),
        migrations.AddConstraint(
            model_name='customerinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('created_by_label', ''), _negated=True), name='customer_invitation_actor_label_required'),
        ),
    ]
