# Generated by Django 6.0.4 on 2026-09-04 11:55

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerinvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(editable=False, max_length=64)),
                ('mobile_digest', models.CharField(editable=False, max_length=64)),
                ('source_ip_digest', models.CharField(editable=False, max_length=64)),
                ('outcome', models.CharField(choices=[('CREATED', 'Application created'), ('IGNORED', 'Request accepted without creating an application')], max_length=10)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempted_at', '-pk'],
                'indexes': [models.Index(fields=['source_ip_digest', 'attempted_at'], name='customer_reg_attempt_ip_idx'), models.Index(fields=['email_digest', 'attempted_at'], name='customer_reg_attempt_email_idx'), models.Index(fields=['mobile_digest', 'attempted_at'], name='cust_reg_attempt_mobile_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['CREATED', 'IGNORED'])), name='customer_registration_attempt_outcome_valid')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_EMAIL_VERIFICATION', 'Pending email verification'), ('AWAITING_OWNER_APPROVAL', 'Awaiting owner approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING_EMAIL_VERIFICATION', max_length=32)),
                ('email_token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('email_verification_expires_at', models.DateTimeField()),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_failed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.CharField(blank=True, max_length=100)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(max_length=40)),
                ('privacy_version', models.CharField(max_length=40)),
                ('consent_accepted_at', models.DateTimeField()),
                ('source_ip_digest', models.CharField(editable=False, max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_label', models.CharField(blank=True, max_length=254)),
                ('review_reason', models.TextField(blank=True)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_customer_registration', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_customer_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='customer_reg_status_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_EMAIL_VERIFICATION', 'AWAITING_OWNER_APPROVAL', 'APPROVED', 'REJECTED', 'EXPIRED'])), name='customer_registration_status_valid'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('status__in', ['PENDING_EMAIL_VERIFICATION', 'AWAITING_OWNER_APPROVAL'])), name='customer_registration_active_email_unique'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_EMAIL_VERIFICATION', 'AWAITING_OWNER_APPROVAL'])), fields=('mobile_number',), name='customer_registration_active_mobile_unique'), models.CheckConstraint(condition=models.Q(models.Q(('approved_user__isnull', True), ('email_verified_at__isnull', True), ('mobile_verified_at__isnull', True), ('review_reason', ''), ('reviewed_at__isnull', True), ('reviewed_by_label', ''), ('status', 'PENDING_EMAIL_VERIFICATION')), models.Q(('approved_user__isnull', True), ('email_verified_at__isnull', True), ('mobile_verified_at__isnull', True), ('review_reason', ''), ('reviewed_at__isnull', True), ('reviewed_by_label', ''), ('status', 'EXPIRED')), models.Q(('approved_user__isnull', True), ('email_verified_at__isnull', False), ('mobile_verified_at__isnull', True), ('review_reason', ''), ('reviewed_at__isnull', True), ('reviewed_by_label', ''), ('status', 'AWAITING_OWNER_APPROVAL')), models.Q(('approved_user__isnull', False), ('email_verified_at__isnull', False), ('mobile_verified_at__isnull', False), ('review_reason__gt', ''), ('reviewed_at__isnull', False), ('reviewed_by_label__gt', ''), ('status', 'APPROVED')), models.Q(('approved_user__isnull', True), ('email_verified_at__isnull', False), ('review_reason__gt', ''), ('reviewed_at__isnull', False), ('reviewed_by_label__gt', ''), ('status', 'REJECTED')), _connector='OR'), name='customer_registration_lifecycle_valid')],
            },
        ),
    ]
