# Generated by Django 6.0.4 on 2026-09-07 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerregistrationattempt_customerregistration'),
        ('schemes', '0020_scheme_enrolment_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountDeletionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(editable=False, max_length=64)),
                ('source_ip_digest', models.CharField(editable=False, max_length=64)),
                ('outcome', models.CharField(choices=[('CREATED', 'Deletion request created'), ('IGNORED', 'Request accepted without creating a deletion request')], max_length=10)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempted_at', '-pk'],
                'indexes': [models.Index(fields=['source_ip_digest', 'attempted_at'], name='acct_del_attempt_ip_idx'), models.Index(fields=['email_digest', 'attempted_at'], name='acct_del_attempt_email_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['CREATED', 'IGNORED'])), name='account_deletion_attempt_outcome_valid')],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_email', models.EmailField(max_length=254)),
                ('email_digest', models.CharField(editable=False, max_length=64)),
                ('source_ip_digest', models.CharField(editable=False, max_length=64)),
                ('verification_token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('PUBLIC', 'Public email verification'), ('AUTHENTICATED', 'Authenticated customer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('CONTAINED', 'Account contained'), ('AWAITING_SETTLEMENT', 'Awaiting settlement or review'), ('APPROVED', 'Approved for final disposition'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_RETENTION', 'Completed with retained records'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='PENDING_VERIFICATION', max_length=32)),
                ('policy_version', models.CharField(max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verification_expires_at', models.DateTimeField()),
                ('verification_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_delivery_failed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_delivery_error', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('owner_review_due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_deletion_requests', to='schemes.customer')),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountDeletionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('AWAITING_SETTLEMENT', 'Awaiting settlement or retention review')], max_length=32)),
                ('reason', models.TextField()),
                ('retained_categories', models.TextField(blank=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(max_length=40)),
                ('decided_by_label', models.CharField(max_length=254)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_deletion_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='accounts.customeraccountdeletionrequest')),
            ],
            options={
                'ordering': ['-decided_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountDeletionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REQUESTED', 'Request created'), ('VERIFICATION_EMAIL_ACCEPTED', 'Verification email accepted'), ('VERIFICATION_EMAIL_FAILED', 'Verification email failed'), ('VERIFIED', 'Request verified'), ('SESSIONS_REVOKED', 'Sessions revoked'), ('GOOGLE_LINK_REMOVED', 'Google link removed'), ('CONTAINED', 'Account contained'), ('OWNER_HOLD_RECORDED', 'Owner hold recorded'), ('OWNER_REJECTED', 'Owner rejected request'), ('NOTICE_ACCEPTED', 'Customer notice accepted'), ('NOTICE_FAILED', 'Customer notice failed')], max_length=40)),
                ('actor_label', models.CharField(max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_deletion_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='accounts.customeraccountdeletionrequest')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='customeraccountdeletionrequest',
            index=models.Index(fields=['status', 'requested_at'], name='acct_del_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccountdeletionrequest',
            index=models.Index(fields=['customer', 'requested_at'], name='acct_del_customer_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['PUBLIC', 'AUTHENTICATED'])), name='account_deletion_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requested_email', ''), _negated=True), models.Q(('policy_version', ''), _negated=True)), name='account_deletion_request_identity_policy_required'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_VERIFICATION', 'VERIFIED', 'CONTAINED', 'AWAITING_SETTLEMENT', 'APPROVED', 'COMPLETED', 'COMPLETED_WITH_RETENTION', 'REJECTED', 'WITHDRAWN', 'EXPIRED'])), name='account_deletion_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('contained_at__isnull', True), ('status', 'PENDING_VERIFICATION'), ('verified_at__isnull', True)), models.Q(('closed_at__isnull', True), ('contained_at__isnull', True), ('status', 'VERIFIED'), ('verified_at__isnull', False)), models.Q(('closed_at__isnull', True), ('contained_at__isnull', False), ('status__in', ['CONTAINED', 'AWAITING_SETTLEMENT', 'APPROVED']), ('verified_at__isnull', False)), models.Q(('closed_at__isnull', False), ('contained_at__isnull', False), ('status__in', ['COMPLETED', 'COMPLETED_WITH_RETENTION', 'REJECTED']), ('verified_at__isnull', False)), models.Q(('closed_at__isnull', False), ('status__in', ['WITHDRAWN', 'EXPIRED'])), _connector='OR'), name='account_deletion_lifecycle_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_VERIFICATION', 'VERIFIED', 'CONTAINED', 'AWAITING_SETTLEMENT', 'APPROVED'])), fields=('customer',), name='account_deletion_one_open_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', 'AWAITING_SETTLEMENT')), name='account_deletion_decision_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), _negated=True), models.Q(('decided_by_label', ''), _negated=True)), name='account_deletion_decision_actor_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('retained_categories__gt', ''), ('review_due_at__isnull', False)), name='account_deletion_decision_review_shape_valid'),
        ),
        migrations.AddIndex(
            model_name='customeraccountdeletionaction',
            index=models.Index(fields=['request', 'created_at'], name='acct_del_action_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['REQUESTED', 'VERIFICATION_EMAIL_ACCEPTED', 'VERIFICATION_EMAIL_FAILED', 'VERIFIED', 'SESSIONS_REVOKED', 'GOOGLE_LINK_REMOVED', 'CONTAINED', 'OWNER_HOLD_RECORDED', 'OWNER_REJECTED', 'NOTICE_ACCEPTED', 'NOTICE_FAILED'])), name='account_deletion_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionaction',
            constraint=models.CheckConstraint(condition=models.Q(('actor_label', ''), _negated=True), name='account_deletion_action_actor_required'),
        ),
    ]
