# Generated by Django 6.0.4 on 2026-09-10 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_account_deletion_foundation'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountDeletionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customeraccountdeletionaction',
            name='account_deletion_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='customeraccountdeletiondecision',
            name='account_deletion_decision_outcome_valid',
        ),
        migrations.AddField(
            model_name='customeraccountdeletiondecision',
            name='disposition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_erased_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccountdeletionaction',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Request created'), ('VERIFICATION_EMAIL_ACCEPTED', 'Verification email accepted'), ('VERIFICATION_EMAIL_FAILED', 'Verification email failed'), ('VERIFIED', 'Request verified'), ('SESSIONS_REVOKED', 'Sessions revoked'), ('GOOGLE_LINK_REMOVED', 'Google link removed'), ('CONTAINED', 'Account contained'), ('OWNER_HOLD_RECORDED', 'Owner hold recorded'), ('OWNER_REJECTED', 'Owner rejected request'), ('NOTICE_ACCEPTED', 'Customer notice accepted'), ('NOTICE_FAILED', 'Customer notice failed'), ('DATA_MINIMIZED', 'Eligible account data removed'), ('COMPLETED_WITH_RETENTION', 'Completed with retained records'), ('RETENTION_REVIEWED', 'Retention reviewed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customeraccountdeletiondecision',
            name='outcome',
            field=models.CharField(choices=[('AWAITING_SETTLEMENT', 'Awaiting settlement or retention review'), ('COMPLETED_WITH_RETENTION', 'Completed with retained records'), ('RETENTION_REVIEW', 'Retention reviewed')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['REQUESTED', 'VERIFICATION_EMAIL_ACCEPTED', 'VERIFICATION_EMAIL_FAILED', 'VERIFIED', 'SESSIONS_REVOKED', 'GOOGLE_LINK_REMOVED', 'CONTAINED', 'OWNER_HOLD_RECORDED', 'OWNER_REJECTED', 'NOTICE_ACCEPTED', 'NOTICE_FAILED', 'DATA_MINIMIZED', 'COMPLETED_WITH_RETENTION', 'RETENTION_REVIEWED'])), name='account_deletion_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['AWAITING_SETTLEMENT', 'COMPLETED_WITH_RETENTION', 'RETENTION_REVIEW'])), name='account_deletion_decision_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'COMPLETED_WITH_RETENTION')), fields=('request',), name='account_deletion_one_completion'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', 'AWAITING_SETTLEMENT'), models.Q(('disposition', {}), _negated=True), _connector='OR'), name='account_deletion_disposition_required'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('privacy_erased_at__isnull', True), models.Q(('email__endswith', '@deleted.invalid'), ('first_name', ''), ('is_active', False), ('is_staff', False), ('is_superuser', False), ('last_login__isnull', True), ('last_name', ''), ('password__startswith', '!'), ('role', 'CUSTOMER'), ('username__startswith', 'deleted-')), _connector='OR'), name='erased_login_is_unusable'),
        ),
        migrations.AddField(
            model_name='customeraccountdeletionnotice',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notice', to='accounts.customeraccountdeletiondecision'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountdeletionnotice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), models.Q(('recipient_email', ''), _negated=True)), models.Q(('accepted_at__isnull', False), ('last_error', ''), ('recipient_email', '')), _connector='OR'), name='deletion_notice_recipient_lifecycle'),
        ),
    ]
