# Generated by Django 6.0.4 on 2026-09-09 19:36

import blog.models
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A concise introduction to the jewellery journal.')),
            ],
            options={
                'verbose_name': 'blog index page',
            },
            bases=(blog.models.PublicBlogGateMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('publication_date', models.DateField(default=django.utils.timezone.localdate)),
                ('author_name', models.CharField(default='Jai Sri Krishna Jewellery', help_text='Public byline shown on the article.', max_length=120)),
                ('summary', models.CharField(help_text='A short, factual introduction shown in article listings.', max_length=280)),
                ('body', wagtail.fields.RichTextField(help_text='Business-authored educational or editorial content only. Do not enter Scheme Rates, customer-specific advice, or authoritative plan terms.')),
                ('featured_image_alt', models.CharField(blank=True, max_length=160)),
                ('featured', models.BooleanField(default=False)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_featured_placements', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'blog post',
            },
            bases=(blog.models.PublicBlogGateMixin, 'wagtailcore.page'),
        ),
    ]
