# Generated by Django 6.0.4 on 2026-08-24 11:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import modelcluster.fields
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A concise introduction shown above the product catalogue.')),
            ],
            options={
                'verbose_name': 'catalogue index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_productcategory_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name': 'product collection',
                'verbose_name_plural': 'product collections',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_productcollection_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('product_code', models.CharField(help_text='Stable internal catalogue reference, for example JSK-G-001.', max_length=40)),
                ('short_description', models.CharField(max_length=280)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('display_price_inr', models.DecimalField(blank=True, decimal_places=2, help_text='Optional informational catalogue price in INR. This is not a Scheme Rate, customer entitlement, invoice, or online checkout price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('enquiry_note', models.CharField(default='Contact our Vellore showroom for current availability and final price.', max_length=240)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory')),
                ('collections', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='products', to='catalog.productcollection')),
            ],
            options={
                'verbose_name': 'product page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(help_text='Describe the jewellery for customers who cannot see the image.', max_length=160)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_placements', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.productpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='productpage',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('product_code'), name='catalog_product_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='productpage',
            constraint=models.CheckConstraint(condition=models.Q(('display_price_inr__isnull', True), ('display_price_inr__gt', 0), _connector='OR'), name='catalog_product_display_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('page', 'image'), name='catalog_product_image_once'),
        ),
    ]
